package com.fis.springjpa.employee;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@RequestMapping(path = "/emp")

public class EmployeeController {
	 @Autowired // This means to get the bean called userRepository
     // Which is auto-generated by Spring, we will use it to handle the data
private EmployeeRepository employeeRepository;

		@PostMapping(path="/add") // Map ONLY POST Requests
		public @ResponseBody String addNewEmployee (@RequestParam String name, @RequestParam String email) {		
			// @ResponseBody means the returned String is the response, not a view name
			// @RequestParam means it is a parameter from the GET or POST request
		
			Employee e = new Employee();
			e.setName(name);
			e.setEmail(email);
			employeeRepository.save(e);
			return "Saved";
		}
		
		@GetMapping(path="/all")
		  public @ResponseBody Iterable<Employee> getAllEmployees() {
		    // This returns a JSON or XML with the users
		    return employeeRepository.findAll();
		  }
			
		
}
